# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtolist',
            name='pubdate',
        ),
    ]
